### PR TITLE
Updated Feed for Episode 26

### PR DESCRIPTION
**Pull request by sockeqwe**

### CODE REVIEW

**Comment by vanniktech** [comment]
I'd really like to have a Git release.

**Comment by ming13** [comment]
@vanniktech, I would strongly recommend to use the website or a podcast application. Download count for GitHub releases varies in `0..30` and it is kind of an overkill to manage this by hand on our side, especially since we want to automate as much as possible (you’ll see much more from us in this direction).

As an alternative, you can use `TheContext/archive` repo — you’ll get audio even faster than the rest of the world. Just don’t tell anyone 😉

**Comment by vanniktech** [comment]
Then automate the release creation.

**Comment by vanniktech** [comment]
(Didn't mean to be passive aggressive or any sorts. Can be interpret that way though - if so that's no my intention).

https://github.com/TheContext/archive/ - seems promising. I subscribed. Thanks!

**Pull request merged**
