### PR TITLE
Feed formatting

### PR DESCRIPTION
**Pull request by Cj-Malone**
I've made some more changed to the feed to better comply with the specs.

The Apple `summary` tag should be plain text, so I've changed it to `encoded` from `content`. I've added some plain text `description`s that iTunes will fall back to certain situations. Amended the `author` information for the latest 2 episodes. And I've added the new Apple `title` tag, based on the updated spec [draft](http://podcasts.apple.com/resources/spec/ApplePodcastsSpecUpdatesiOS11.pdf), potentially `episode` numbers should be adopted as well, but since you have multiple parts to some episodes I don't know how to handle them.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks a lot!
Yes, I have read about the specs too, but was afraid that other podcasting apps do not follow this specification, especially the plain text and content:encoded.

do you have any idea how much standardized this is?

**Comment by Cj-Malone** [comment]
[AntennaPod](https://github.com/AntennaPod/AntennaPod) currently shows the a HTML striped shownotes in the overview when subscribing and correctly shows the shownotes when viewing the page.
HTML striped description current shownotes
With this, AntennaPod shows the a nicely formatted description in the overview and still shows the proper show notes on the page.
description with patch
shownotes with patch

Podcasts (iOS 11) currently badly formatted summary, based on HTML striped description.
HTML striped description
HTML striped description overview
Show notes, click for more
Show notes HTML stripped
With this merged it shows clean titles nice plain text description and HTML show notes.
clean titles
clean plain text descriptions
Show notes without click for more



You can test it by subscribing to [master](https://raw.githubusercontent.com/BetterFeeds/TheContext-Podcast/master/feed.rss) and [formatting](https://raw.githubusercontent.com/BetterFeeds/TheContext-Podcast/formatting/feed.rss) branches.

**Comment by sockeqwe** [comment]
Thanks for the screenshots.
I tried to subscribe formatted branch on PocketCasts (as the majority use that client for listening to our podcast) but somehow pocketcast have indexed the podcast internally and it seems to return master branch rss feed, although I enter formatting branch rss feed.

However, pocketcasts web app renders plain text:

bildschirmfoto 2017-08-07 um 11 59 17

The Android app displays html (as already said, coudnt force pocketcast to load rss feed from formatted branch, maybe because of `	<atom:link rel="self" type="application/rss+xml" href="https://raw.githubusercontent.com/artem-zinnatullin/TheContext-Podcast/master/feed.rss"/>
` in formatted branch rss feed)

**Comment by Cj-Malone** [comment]
Even with changing the self link Pocket Casts still picked it up as the original. I'm temporally hosting it [here](https://feeds.betterfeeds.org/context.rss) with some more edits to ensure it's not classed as the same feed.

Pocket Casts still uses the original titles, shownotes render from HTML however when shared to the web it doesn't show any show notes.

**Comment by sockeqwe** [comment]
Ah ok, seems to still work as expected from android app. PocketCasts web
app does not show show notes http://pca.st/cOJR

Cj Malone <notifications@github.com> schrieb am Mo., 7. Aug. 2017, 13:01:

**Comment by sockeqwe** [comment]
Closed by #108

**Pull request closed without merging**
